version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: pdfjson-backend:latest
    env_file:
      - .env
    ports:
      - "7000:7000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:7000/healthz || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - web

networks:
  web:
    external: true
